# Generated by Django 4.0.6 on 2022-07-25 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa kategorii')),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='nazwa')),
                ('description', models.TextField(verbose_name='opis')),
                ('type', models.PositiveIntegerField(choices=[(2, 'organizacja pozarządowa'), (1, 'funcacja'), (3, 'zbiórka lokalna')], default=1, verbose_name='status organizacji')),
                ('categories', models.ManyToManyField(to='manager.category', verbose_name='kategorie artykułów przyjmowane przez organizację')),
            ],
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('adress', models.CharField(max_length=100, verbose_name='adres zamieszkania')),
                ('phone_number', models.CharField(max_length=15, verbose_name='nr telefonu')),
                ('city', models.CharField(max_length=100, verbose_name='miasto')),
                ('zip_code', models.CharField(max_length=6, verbose_name='kod pocztowy')),
                ('pick_up_date', models.DateField(verbose_name='data odbioru')),
                ('pick_up_time', models.TimeField(verbose_name='czas odbioru')),
                ('pick_up_comment', models.DateTimeField(verbose_name='data komentarza')),
                ('categories', models.ManyToManyField(to='manager.category', verbose_name='kategorie artykułu')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.institution', verbose_name='instytucja przyjmująca')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik')),
            ],
        ),
    ]
