# Generated by Django 4.0.6 on 2022-08-02 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_alter_institution_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_taken',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Ilość worków'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Fundacja'), (3, 'Zbiórka Lokalna'), (2, 'Organizacja Pozarządowa')], default=1, verbose_name='Status organizacji'),
        ),
    ]
