# Generated by Django 4.0.6 on 2022-08-11 16:27

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import manager.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('manager', '0008_donation_is_taken_alter_donation_quantity_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ('is_taken', '-pick_up_date', '-pick_up_time', 'quantity'), 'verbose_name': 'Darowizna', 'verbose_name_plural': 'Darowizny'},
        ),
        migrations.AlterModelOptions(
            name='institution',
            options={'ordering': ('name', 'type', 'description'), 'verbose_name': 'Organizacja', 'verbose_name_plural': 'Organizacje'},
        ),
        migrations.AddField(
            model_name='donation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 8, 11, 16, 27, 41, 848743, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nazwa kategorii'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(max_length=100, validators=[manager.validators.address_regex_validator], verbose_name='adres zamieszkania'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='categories',
            field=models.ManyToManyField(to='manager.category', verbose_name='kategorie artykułu'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='city',
            field=models.CharField(max_length=100, validators=[manager.validators.city_name_regex_validator], verbose_name='miasto'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager.institution', verbose_name='instytucja obdarowywana'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(max_length=15, validators=[manager.validators.phone_regex_validator], verbose_name='nr telefonu'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_comment',
            field=models.TextField(verbose_name='komentarz'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_date',
            field=models.DateField(verbose_name='data odbioru'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='pick_up_time',
            field=models.TimeField(verbose_name='czas odbioru'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='ilość worków'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='user',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='użytkownik'),
        ),
        migrations.AlterField(
            model_name='donation',
            name='zip_code',
            field=models.CharField(max_length=6, validators=[manager.validators.postcode_regex_validator], verbose_name='kod pocztowy'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='categories',
            field=models.ManyToManyField(to='manager.category', verbose_name='kategorie artykułów przyjmowane przez organizację'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='description',
            field=models.TextField(verbose_name='cel organizacji'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nazwa'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Fundacja'), (3, 'Zbiórka Lokalna'), (2, 'Organizacja Pozarządowa')], default=1, verbose_name='status organizacji'),
        ),
    ]
