# Generated by Django 4.0.6 on 2022-08-11 16:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0009_alter_donation_options_alter_institution_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created',
            field=models.DateTimeField(verbose_name=datetime.datetime(2022, 8, 11, 16, 52, 38, 548201, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.PositiveIntegerField(choices=[(3, 'Zbiórka Lokalna'), (2, 'Organizacja Pozarządowa'), (1, 'Fundacja')], default=1, verbose_name='status organizacji'),
        ),
    ]
