# Generated by Django 4.0.6 on 2022-08-13 17:36

from django.db import migrations, models
import manager.validators


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_alter_donation_created_alter_institution_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[manager.validators.phone_regex_validator], verbose_name='nr telefonu'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='type',
            field=models.PositiveIntegerField(choices=[(1, 'Fundacja'), (2, 'Organizacja Pozarządowa'), (3, 'Zbiórka Lokalna')], default=1, verbose_name='status organizacji'),
        ),
    ]
